services:
  - type: web
    name: task-manager-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: mongoURI
        value: mongodb+srv://johnWick:vdNs1xnUCnGGapIR@cluster0.xsnonkp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: ACCESS_TOKEN_SECERT
        value: S23R24M25


